### ISSUE TITLE
Better documentation please?

### ISSUE THREAD

**Issue by Xendergo** [Rio6/Istrolid-js-ai#1]
Can you create better documentation for the library? I'm trying to use it but I don't know what most of the functions do. (for example, what is pos relative to?)

**Comment by F4Tornado** [comment]
I think its a field function, but I'm not sure

**Comment by Xendergo** [comment]
I didn't get very far in writing the documentation, but this is what I got to:

## How to install

1. Install tampermonkey on your browser
2. Click the tampermonkey icon and click "create an new script"
3. Copy this code I asked for [here](https://stackoverflow.com/questions/48999415/simply-require-ing-a-3rd-party-library-results-in-javascript-errors/49000497?noredirect=1#comment85041490_49000497)
```javascript
// ==UserScript==
// @name         Istrolid.com, use Istrolid Javascript AI API
// @version      0.2
// @match        *://www.istrolid.com/game.html*
// @grant        none
// ==/UserScript==

/*-- Wait for game to load.  Try to find an event or node that signals
    this, instead of one or two timers.
*/
var sfStrtTmr  = setInterval(() => {
    if (typeof Interpolator  === "function") {
        clearInterval (sfStrtTmr);
        setTimeout (loadPoorScript, 1111);
    }
}, 333);

function loadPoorScript(url){
    var newNode     = document.createElement('script');
        newNode.onload  = runScriptMain;
    if (!url) {
        newNode.src = "https://rawgit.com/Rio6/Istrolid-js-ai/master/r26Ai.js";
    } else {
        newNode.src = url;
    }
    document.body.appendChild(newNode);
}

**Comment by Xendergo** [comment]
I found the documentation in the R26Ai file

**Comment by Xendergo** [comment]
I'm trying to write documentation myself
