### ISSUE TITLE
My units go invisible when they move

### ISSUE THREAD

**Issue by Xendergo** [Rio6/Istrolid-js-ai#10]
My units go invisible when they spawn in. This is the code:

 ```javascript
// Guard command points
let points = order.findThings(-1, function(target) {
  return target.commandPoint && (target.side == unit.side || target.capping > 0);
});
if (points.length > 0) {
  order.move(points[0]);
}
```

This is the building code:

```javascript
let points = order.findThings(-1, function(target) {
  return target.commandPoint && (target.side == unit.side || target.capping > 0);
});
build.buildUnit(points.length, 3);
```

**Comment by Rio6** [comment]
`findThings` gives you a thing, not a position. Use `order.move(points[0].pos)`.

BTW i re-ordered the parameters from `findThings(range, check, closeTo)` to `findThings(check, range, closeTo)` in the newest commit so you dont have to put in `-1` when looking for everything.

**Comment by Xendergo** [comment]
I also notice that you change it to `build.buildUnits()`

**Comment by Xendergo** [comment]
This is proof that I am a professional idiot
