### ISSUE TITLE
2 errors, probably related

### ISSUE THREAD

**Issue by Xendergo** [Rio6/Istrolid-js-ai#11]
1.  I get this error:
`
TypeError: Cannot read property '0' of undefined R26Ai.js:149`

2. movement.spread() not spreading correctly

![2018-03-28 1](https://user-images.githubusercontent.com/25280710/38063093-5558a138-32c5-11e8-9bad-bd5e0b283727.png)

The issue occurred when I completely owned the black one in the picture, and all 4 command points were being selected.

Both the problems involve this code:

```javascript
let points = order.findThings(function(target) {
   return target.commandPoint && (target.side == unit.side);
});
if (points.length > 0) {
  let point = movement.spread(points)
  order.move(movement.inRange(point.pos, point.radius));
}
```

**Comment by Rio6** [comment]
`movement.inRange()` doesn't return anything if the unit is already in range.
I added a null check in `order.move()` in 1c867b4dcf09e3e155beb81a0eaf022a78b916f6

**Comment by Xendergo** [comment]
That only fixes the first issue.

![2018-03-28 2](https://user-images.githubusercontent.com/25280710/38065520-bd6ceebc-32d1-11e8-8dd2-84b8a77eec99.png)

**Comment by Rio6** [comment]
try fb01b2176283f6bd776a6b4221be876a9a6920b2
