### ISSUE TITLE
Is there a way to prioritize human commands over AI commands?

### ISSUE THREAD

**Issue by Xendergo** [Rio6/Istrolid-js-ai#12]
When I move something, I have to spam the right click button until it gets to where I want it to be. Is there a way to fix that?

**Comment by Rio6** [comment]
Ther's currently no way to tell the difference between ai command and maunal command, since this api simulates human commands.

For now, you can try checking the length or content of `order.getUnitOrders()` before you run ai commands.

**Comment by Xendergo** [comment]
That would explain why I can see arrows where the ships are going using your library, but not when using the built in AI

**Comment by Rio6** [comment]
Built in ai used to show arrows, but devs removed it to reduce bandwidth.

**Comment by Rio6** [comment]
I made a function to check if a unit has player order queued in 7e56c839cb9a5a1982e48e73e1e89bbf690874b7

I haven't test it in multiplayer mode

**Comment by Rio6** [comment]
Tested and fixed in ae53ae5893e2a84f4c45f4d67795cd4e47eed2e0
