### ISSUE TITLE
What are the properties for unit?

### ISSUE THREAD

**Issue by Xendergo** [Rio6/Istrolid-js-ai#3]
Also, how did you get the code to run on steam?

**Comment by Rio6** [comment]
Select a ship then type `console.log(commander.selection[0]);` to see a unit's properties when it's on field.
Use `console.log(buildBar.specToUnit(commander.buildBar[0]));` to see the properties of the unit in your first slot.

**Comment by Rio6** [comment]
You can just copy the whole code into the console.
If you want it to load automatically, find a way to unpack app.asar, put your scripts in the js folder, then add `<script src="js/yourscript.js"></script>` in game.html after the game script tag.

**Comment by Xendergo** [comment]
I unpakaged the app.asar, put the things in (I put the library and code in separate files for readability), and I get 2 errors:

Uncaught TypeError: Cannot read property 'things' of null  R26Ai.js:206
Uncaught TypeError: Cannot read property 'number' of null  R26Ai.js:121

With this code:

```javascript
console.log("r26Ai: ", r26Ai);

r26Ai.clearAiRule();

r26Ai.addAiRule({
  filter: function(unit) {
    return unit.name === "conquerer";
  },
  ai: function(unit) {
    this.rule = function() {
      order.move([0, 0]);
    }
  },
  build: function(unit) {
    build.buildUnit(4, 1);
  }
})

r26Ai.enabled = true;
```

I also tried with the example code

**Comment by Rio6** [comment]
Fixed in commit 48f0238d7ee983c94d59df74f59d8e300acad2f8

**Comment by Xendergo** [comment]
Now it doesn't do anything at all

**Comment by Rio6** [comment]
```javascript
ai: function(unit) {
    this.run = function() {
      order.move([0, 0]);
    }
  }
```
not
```javascript
ai: function(unit) {
    this.rule = function() {
      order.move([0, 0]);
    }
  }
```

**Comment by Xendergo** [comment]
thats what I had before
```javascript

r26Ai.addAiRule({
  filter: function(unit) {
    console.log(unit, "UNIT");
    return unit.name === "Conquerer";
  },
  ai: function(unit) {
    this.run = function() {
      order.move([0, 0]);
    }
  },
  build: function(unit) {
    build.buildUnit(4, 1);
  }
});

```

**Comment by Rio6** [comment]
is that your whole file?

**Comment by Xendergo** [comment]
yeah

**Comment by Rio6** [comment]
did you enabled it?
```
r26Ai.enabled = true;
```

**Comment by Xendergo** [comment]
No

**Comment by Xendergo** [comment]
I added that in and it works now!

Also, I got useful stuff when console.logging unit.
