### ISSUE TITLE
Function to avoid DPS danger zones?

### ISSUE THREAD

**Issue by Xendergo** [Rio6/Istrolid-js-ai#6]
I'm trying to port my current AI to this, but there isn't a function for avoiding danger zones, like there is for avoiding shots.

**Comment by Rio6** [comment]
avoid dps in the game is bascally
```
var enemy = order.findThings(3000, e => e.weaponDPS * 16 > dps)[0];
var dest = movement.fleeRange(enemy.pos, enemy.weaponRange);
```

**Comment by Xendergo** [comment]
Why *16?

**Comment by Rio6** [comment]
Because it is actually stored as damage per tick, there's 16 ticks per second
