### ISSUE TITLE
How do you create functions?

### ISSUE THREAD

**Issue by Xendergo** [Rio6/Istrolid-js-ai#7]
I've made a function that keeps a certain number of units on screen. How can I put that in the library without breaking it?

**Comment by Rio6** [comment]
i just made the same function too XD

Just add functions in whatever namespace it fits if you want, it's ok if you break it a bit since theres only 2 ppl using rn

**Comment by Xendergo** [comment]
No, it really breaks, with these errors: (remember these?)

```
Uncaught TypeError: Cannot read property 'things' of null R26Ai.js:206
Uncaught TypeError: Cannot read property 'number' of null R26Ai.js:121
```

ps
That function is SUPER confusingly named

**Comment by Rio6** [comment]
Can't think of a less confusing name

**Comment by Xendergo** [comment]
I made a pull request

**Comment by Xendergo** [comment]
No, I edited the file, but forgot to make a pull request

**Comment by Xendergo** [comment]
there

**Comment by Xendergo** [comment]
I've updated the docs BTW
